## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [7]:
a= np.array([[1,5,1,85,3,1,54],[3,4,2,3,5,5,3]])
b= np.array([[2,3,3,4,5,32,3],[2,5,8,2,7,5,3]])
c= a*b
print(c)

[[  2  15   3 340  15  32 162]
 [  6  20  16   6  35  25   9]]


In [8]:
c= np.multiply(a,b)
print(c)

[[  2  15   3 340  15  32 162]
 [  6  20  16   6  35  25   9]]


## Write a NumPy program to compute the determinant of a given square array

In [9]:
a= np.array([[1,5,1,85,3,1,54],[3,4,2,3,5,5,3]])
w= np.square(a)
print(w)


[[   1   25    1 7225    9    1 2916]
 [   9   16    4    9   25   25    9]]


## Write a NumPy program to compute the cross product of two given vectors

In [18]:
e=[[1,2,3],[1,2,3]]
r=[[1,2,4],[1,2,4]]
s= np.cross(e,r)
print(s)

[[ 2 -1  0]
 [ 2 -1  0]]


## Write a NumPy program to compute the condition number of a given matrix
the condition number of a function measures how much the output value of the function can change for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, and how much error in the output results from an error in the input.

*hint: look for something similar in the `linalg` module*

In [2]:
d= np.array([ [1,5,1,5],
              [3,4,2,3],
              [2,3,3,4],
              [2,5,8,2],
              ])
j= np.linalg.cond(d)
print(j)

10.856660053952611


## Write a NumPy program to compute the inverse of a given matrix

In [29]:
y= np.array([ [1,5,1,5],
              [3,4,2,3],
              [2,3,3,4],
              [2,5,8,2],
              ])
z= np.linalg.inv(y)
print(z)






[[-0.30246914  0.4382716   0.10493827 -0.11111111]
 [ 0.24691358  0.17283951 -0.49382716  0.11111111]
 [-0.08641975 -0.16049383  0.17283951  0.11111111]
 [ 0.0308642  -0.22839506  0.4382716  -0.11111111]]
